#!/bin/bash
mkdir ~/test && {
echo "catalog test was created successfully" > ~/report
name=$(ps -o lstart $$ | tail -n1)
touch ~/test/"$name"
}
ping www.net_nikogo.ru || echo "$(date +"%F_%H:%M") host is not available" >> ~/report
